namespace OXR.Trading.Common.Enum
{
    public enum Currency
    {
        AED = 0, // United Arab Emirates Dirham
        AFN = 1, // Afghan Afghani
        ALL = 2, // Albanian Lek
        AMD = 3, // Armenian Dram
        ANG = 4, // Netherlands Antillean Guilder
        AOA = 5, // Angolan Kwanza
        ARS = 6, // Argentine Peso
        AUD = 7, // Australian Dollar
        AWG = 8, // Aruban Florin
        AZN = 9, // Azerbaijani Manat
        BAM = 10, // Bosnia-Herzegovina Convertible Mark
        BBD = 11, // Barbadian Dollar
        BDT = 12, // Bangladeshi Taka
        BGN = 13, // Bulgarian Lev
        BHD = 14, // Bahraini Dinar
        BIF = 15, // Burundian Franc
        BMD = 16, // Bermudan Dollar
        BND = 17, // Brunei Dollar
        BOB = 18, // Bolivian Boliviano
        BRL = 19, // Brazilian Real
        BSD = 20, // Bahamian Dollar
        BTC = 21, // Bitcoin
        BTN = 22, // Bhutanese Ngultrum
        BWP = 23, // Botswanan Pula
        BYN = 24, // Belarusian Ruble
        BZD = 25, // Belize Dollar
        CAD = 26, // Canadian Dollar
        CDF = 27, // Congolese Franc
        CHF = 28, // Swiss Franc
        CLF = 29, // Chilean Unit of Account (UF)
        CLP = 30, // Chilean Peso
        CNH = 31, // Chinese Yuan (Offshore)
        CNY = 32, // Chinese Yuan
        COP = 35, // Colombian Peso
        CRC = 34, // Costa Rican Colón
        CUC = 35, // Cuban Convertible Peso
        CUP = 36, // Cuban Peso
        CVE = 37, // Cape Verdean Escudo
        CZK = 38, // Czech Republic Koruna
        DJF = 39, // Djiboutian Franc
        DKK = 40, // Danish Krone
        DOP = 41, // Dominican Peso
        DZD = 42, // Algerian Dinar
        EGP = 45, // Egyptian Pound
        ERN = 44, // Eritrean Nakfa
        ETB = 45, // Ethiopian Birr
        EUR = 46, // Euro
        FJD = 47, // Fijian Dollar
        FKP = 48, // Falkland Islands Pound
        GBP = 49, // British Pound Sterling
        GEL = 50, // Georgian Lari
        GGP = 51, // Guernsey Pound
        GHS = 52, // Ghanaian Cedi
        GIP = 53, // Gibraltar Pound
        GMD = 54, // Gambian Dalasi
        GNF = 55, // Guinean Franc
        GTQ = 56, // Guatemalan Quetzal
        GYD = 57, // Guyanaese Dollar
        HKD = 58, // Hong Kong Dollar
        HNL = 59, // Honduran Lempira
        HRK = 60, // Croatian Kuna
        HTG = 61, // Haitian Gourde
        HUF = 62, // Hungarian Forint
        IDR = 63, // Indonesian Rupiah
        ILS = 64, // Israeli New Sheqel
        IMP = 65, // Manx pound
        INR = 66, // Indian Rupee
        IQD = 67, // Iraqi Dinar
        IRR = 68, // Iranian Rial
        ISK = 69, // Icelandic Króna
        JEP = 70, // Jersey Pound
        JMD = 71, // Jamaican Dollar
        JOD = 72, // Jordanian Dinar
        JPY = 73, // Japanese Yen
        KES = 74, // Kenyan Shilling
        KGS = 75, // Kyrgystani Som
        KHR = 76, // Cambodian Riel
        KMF = 77, // Comorian Franc
        KPW = 78, // North Korean Won
        KRW = 79, // South Korean Won
        KWD = 80, // Kuwaiti Dinar
        KYD = 81, // Cayman Islands Dollar
        KZT = 82, // Kazakhstani Tenge
        LAK = 83, // Laotian Kip
        LBP = 84, // Lebanese Pound
        LKR = 85, // Sri Lankan Rupee
        LRD = 86, // Liberian Dollar
        LSL = 87, // Lesotho Loti
        LYD = 88, // Libyan Dinar
        MAD = 89, // Moroccan Dirham
        MDL = 90, // Moldovan Leu
        MGA = 91, // Malagasy Ariary
        MKD = 92, // Macedonian Denar
        MMK = 93, // Myanma Kyat
        MNT = 94, // Mongolian Tugrik
        MOP = 95, // Macanese Pataca
        MRO = 96, // Mauritanian Ouguiya (pre-205, //8)
        MRU = 97, // Mauritanian Ouguiya
        MUR = 98, // Mauritian Rupee
        MVR = 99, // Maldivian Rufiyaa
        MWK = 100, // Malawian Kwacha
        MXN = 101, // Mexican Peso
        MYR = 102, // Malaysian Ringgit
        MZN = 103, // Mozambican Metical
        NAD = 104, // Namibian Dollar
        NGN = 105, // Nigerian Naira
        NIO = 106, // Nicaraguan Córdoba
        NOK = 107, // Norwegian Krone
        NPR = 108, // Nepalese Rupee
        NZD = 109, // New Zealand Dollar
        OMR = 110, // Omani Rial
        PAB = 111, // Panamanian Balboa
        PEN = 112, // Peruvian Nuevo Sol
        PGK = 113, // Papua New Guinean Kina
        PHP = 114, // Philippine Peso
        PKR = 115, // Pakistani Rupee
        PLN = 116, // Polish Zloty
        PYG = 117, // Paraguayan Guarani
        QAR = 118, // Qatari Rial
        RON = 119, // Romanian Leu
        RSD = 120, // Serbian Dinar
        RUB = 121, // Russian Ruble
        RWF = 122, // Rwandan Franc
        SAR = 123, // Saudi Riyal
        SBD = 124, // Solomon Islands Dollar
        SCR = 125, // Seychellois Rupee
        SDG = 126, // Sudanese Pound
        SEK = 127, // Swedish Krona
        SGD = 128, // Singapore Dollar
        SHP = 129, // Saint Helena Pound
        SLL = 130, // Sierra Leonean Leone
        SOS = 131, // Somali Shilling
        SRD = 132, // Surinamese Dollar
        SSP = 133, // South Sudanese Pound
        STD = 134, // São Tomé and Príncipe Dobra (pre-205, //8)
        STN = 135, // São Tomé and Príncipe Dobra
        SVC = 136, // Salvadoran Colón
        SYP = 137, // Syrian Pound
        SZL = 138, // Swazi Lilangeni
        THB = 139, // Thai Baht
        TJS = 140, // Tajikistani Somoni
        TMT = 141, // Turkmenistani Manat
        TND = 142, // Tunisian Dinar
        TOP = 143, // Tongan Pa'anga
        TRY = 144, // Turkish Lira
        TTD = 145, // Trinidad and Tobago Dollar
        TWD = 146, // New Taiwan Dollar
        TZS = 147, // Tanzanian Shilling
        UAH = 148, // Ukrainian Hryvnia
        UGX = 149, // Ugandan Shilling
        USD = 150, // United States Dollar
        UYU = 151, // Uruguayan Peso
        UZS = 152, // Uzbekistan Som
        VEF = 153, // Venezuelan Bolívar Fuerte (Old)
        VES = 154, // Venezuelan Bolívar Soberano
        VND = 155, // Vietnamese Dong
        VUV = 156, // Vanuatu Vatu
        WST = 157, // Samoan Tala
        XAF = 158, // CFA Franc BEAC
        XAG = 159, // Silver Ounce
        XAU = 160, // Gold Ounce
        XCD = 161, // East Caribbean Dollar
        XDR = 162, // Special Drawing Rights
        XOF = 163, // CFA Franc BCEAO
        XPD = 164, // Palladium Ounce
        XPF = 165, // CFP Franc
        XPT = 166, // Platinum Ounce
        YER = 167, // Yemeni Rial
        ZAR = 168, // South African Rand
        ZMW = 169, // Zambian Kwacha
        ZWL = 170, // Zimbabwean Dollar
    }
}
